### PR TITLE
re-add wordnet PR

### PR DESCRIPTION
**Pull request by kylepjohnson**
@wmshort this is a copy-paste of your PR at https://github.com/cltk/cltk/pull/945 

In the next comment, I will point out a few specifics for you.

### CODE REVIEW

**Comment by kylepjohnson** [comment]
@wmshort I recommend taking the following steps, in this order:
- Clone this repo
- `git checkout -b kylepjohnson-add-wn master`
- `git pull https://github.com/kylepjohnson/cltkv1.git add-wn`
- Install Python 3.7 if you don't have it already
- make a virtual environment, but make sure not to include it in this repo
- I added your code to `src/cltkv1/wordnet/wordnet.py`. To experiment, you can add your API calls to the `__main__` at the bottom (as you already were doing)
- Take a look also at the very top of this file, to which I added your documentation from the docs page. For now, do not bother with a special docs file, but put everything you want people to know in this module.
- See the detailed note for you [at this line](https://github.com/cltk/cltkv1/pull/62/files#diff-94d4218ba2b1f130c68e14a9de830ed5R12). I provide these examples as an idea, but you know what the I/O should be.
- Finally, based upon our conversation today, I recommend that your class `WordNetCorpusReader` takes a required argument to declare language. So you do something like:

``` python
>>> latin_wn = WordNetCorpusReader(iso_code="lat")
>>> latin_wn.synset('n#03457380')
Synset(pos='n', offset='03457380', definition='a cutting or thrusting weapon with a long blade')
```

There is one outstanding question for me, though you might have the answer: *What is the single most important class or method?* If there are more than one, that's OK, but let me know. From my vantage, I think `.synsets()` is definitely valuable. The reason I ask is this will determine the operations for which I write a `WordNetProcess`. I will do this work once you're finished, so don't worry about implementation -- just communicate with me which ones you want to provide to our general users.

**Comment by wmshort** [comment]
This looks great. I’m starting now to work through everything. Yes, the synsets are the most immediate main entry point to the semantic data. However, I think the interface that is probably most useful to users is via the lemmas – and then the synsets. In other words, as a user is doing text analysis they are dealing with sequences of words and then need to access the senses of those individual words, a word’s lexical relations, or the semantic relations that are traceable via its synsets. In this perspective the Lemma is the perhaps the entry point. I actually think that the most useful thing would be to devise a way to work it directly into the pipeline – so that, given a Document with its stream of Lemma tokens (Omnis Gallia divisa est . . . ) it is possible to access the semantic information directly via the Lemma object itself (or whatever the equivalent is), just as you would want to be able to access morphological information about tokens etc.
William Michael Short
Lecturer in Classics & Ancient History
University of Exeter
Phone: 01392 724794
E-mail: w.short@exeter.ac.uk
Amory Building, Rennes Drive, Exeter, Devon, EX4 4RJ
Ancient Greek WordNet<https://greekwordnet.chs.harvard.edu/> | Latin WordNet<https://latinwordnet.exeter.ac.uk/> | Cylleneus: Next-gen corpus search for ancient languages<https://github.com/cylleneus>
[http://www.exeter.ac.uk/codebox/email-sig/staff-sig.gif]
This email and any attachment may contain information that is confidential, privileged, or subject to copyright, and which may be exempt from disclosure under applicable legislation. It is intended for the addressee only. If you received this message in error, please let me know and delete the email and any attachments immediately. The University will not accept responsibility for the accuracy/completeness of this email and its attachments.

**Comment by kylepjohnson** [comment]
Hi Bill, combining a few comments from your email here, too.

> what do I need to return from the algorithm and run methods

Don't worry about implementing the WordNetProcess for now, just focus on getting your API ls right. We'll implement Process together (frankly not intuitive at first blush).

> to extract the word.lemma for each and then grab the synsets for that lemma from the WordNet

Yes, that is exactly right.

> I think the interface that is probably most useful to users is via the lemmas – and then the synsets

> In this perspective the Lemma is the perhaps the entry point

Agreed :)

**Possibly important question:**

In [your declaration of WordNetCorpusReader.lemma()](https://github.com/cltk/cltkv1/pull/62/files#diff-94d4218ba2b1f130c68e14a9de830ed5R1714), you have 3 required params (lemma, pos, morpho). Is it possible to only require **only the lemma?** The reason I ask is that, while we might expect to often have such tags, (a) there's bound to be some mistakes in the prediction and (b) the format of these tags varies depending on the treebank set used to train the tagger.

Please tell me if I am confused, but would it be possible to make an api similar to the following?

``` python
wordnet_latin = WordNetCorpusRead(iso_code="lat")
wn_lemma = wordnet_latin.lemma("uirtus")
wn_lemma.get_synsets("virtus")
[Synset(pos='n', offset='05595229', definition='feeling no fear'), Synset(pos='n', offset='04504076', definition='a characteristic property that defines the apparent individual nature of something'), …]
```

When your WN Process is added to a user's Pipeline, then it would create a new key-val pair, resulting in something like:

``` python
Word(string="uirtute", lemma="uirtus", pos="ablative", synsets=[Synset(pos='n', offset='05595229', definition='feeling no fear'), …])
```


All this said, you can have whatever API to your classes/methods you see fit. I am thinking from the perspective of the Process (ie as a consumer of your tool). We'll need 1 general-purpose interface for that, then of course you'll have docs to allow your advanced users to do more specialized tasks.

**Comment by kylepjohnson** [comment]
Looking at [the NLTK docs](https://www.nltk.org/howto/wordnet.html), here's the most basic API they offer, which is what I have in mind:

``` python
>>> wn.synsets('dog')
[Synset('dog.n.01'), Synset('frump.n.01'), Synset('dog.n.03'), Synset('cad.n.01'),
Synset('frank.n.02'), Synset('pawl.n.01'), Synset('andiron.n.01'), Synset('chase.v.01')]
```

For the sake of the `WordNetProcess` this would be straightforward to implement.

For those who need to do more nuanced work, they could dig into your docs and do their own post-porcessing, or even write their own custom Process. Like this example, which I would consider too specialized for the default `WordNetProcess`, but which you'd want to allow your users to do stuff like this:

``` python
>>> wn.synsets('dog', pos=wn.VERB)
[Synset('chase.v.01')]
```

**Comment by wmshort** [comment]
I’ll put off the question of the Process for now, but it is helpful to keep this in mind when considering the API as it ties directly into the question of the main ‘entry point’. In that respect you’re the question you raise is not just possibly important but crucially important! In looking back over the code I had the same thing in mind, actually. The thing that I keep running up against is this. It seems necessary (including for implementing the WordNetProcess) that the lemma ‘getter’ is deterministic – in the sense that with a given input we want to be certain we returning a single lemma. This isn’t a problem with something like


wn_lemma = wordnet_latin.lemma("uirtus", "n")

or even


wn_lemma = wordnet_latin.lemma("uirtus")

where there is no ambiguity and I would be really happy if we could have the signature be simplified. But how would we handle a case like:


wn_lemma = wordnet_latin.lemma("consularis")



where two lemmas are possible, namely a noun and adjective? In this case, of course, the ambiguity can be resolved by providing the POS in addition, which is available on the Word object.



But there are more challenging cases, like


wn_lemma = wordnet_latin.lemma("dico", "v")

where even this level of specification does not guarantee a single lemma: i.e., dico (-are) vs dico (-ere).

And there are even cases where full specification would nevertheless yield ambiguities:


wn_lemma = wordnet_latin.lemma("dico", "v", "v1spia--3-")

Do we mean accído or áccido? And so on. For this the WordNet relies on the URI.

Obviously if the token stream has been produced from an annotated corpus there would be some further specification that can be taken advantage of. How then do we handle cases where we can’t be certain of the lemmatization question? It’s the usual problem, I guess.

If on the other hand we can be sure that the Lemma (i.e. word.lemma) is already ‘resolved’ and unique then the issue would only be how correctly align this with the WordNet lemma base.

Relatedly: I really like the idea of having .synset() generate the list of synonyms, via the word’s synsets. This narrows down the functionality to the relation of synonym, which is fine. One thing to keep in mind is that in recent generations of the PWN the synsets have been re-designated according to their ‘base’ lemma. So the first (?) synset of the lemma dog is called ‘dog.01’ or something like that. This is why the PWN produces a list of what seem to be lemmas on a call like dog.synsets(). They are sense-definitions named after the base lemma (so ‘chase.v.01’ is the sense ‘to constantly pursue someone’, i.e., to dog someone). I find that this unhelpfully blurs the lemma / sense line – so that actually using synset IDs (pos/offset), while not very human-friendly, actually better captures the idea of senses as being distinct and abstracted away from words. In this way it’s better to talk about the verbal sense of ‘dog’ as being v#12345678 (or whatever) rather than as ‘chase.v.01’ because, well, chase is itself a lemma (with the sense ‘chase’….). So when return a list of synset IDs, we are basically doing the same thing as returning ‘dog.n.01’ (‘a hairy and smelly quadruped’), ‘frank.n.01’ (‘a hotdog’), ‘dog.v.01 (‘to constantly pursue’), but in the PWN this looks more like a set of lemmas than a set of synset ID numbers.

On the other hand, probably the most-used information will precisely be synonyms, so that calling something like uirtus.synset() or .synsets() could very reasonably return ‘audacia’, ‘animus’, etc., i.e., the lemma set(s) for its several senses – understanding that this is an indirect relation, via the shared synset ID.

uirtus --> synset n#12345678 ‘the psychological state of being courageous’, synset n#87654321 ‘moral or ethical excellence’
audacia -> synset n#12345678 ‘the psychological state of being courageous’
animus -> synset n#12345678, synset n#89359181 ‘the mind’ . . . etc for its other senses

All best,
Bill
William Michael Short
Lecturer in Classics & Ancient History
University of Exeter
Phone: 01392 724794
E-mail: w.short@exeter.ac.uk
Amory Building, Rennes Drive, Exeter, Devon, EX4 4RJ
Ancient Greek WordNet<https://greekwordnet.chs.harvard.edu/> | Latin WordNet<https://latinwordnet.exeter.ac.uk/> | Cylleneus: Next-gen corpus search for ancient languages<https://github.com/cylleneus>
[http://www.exeter.ac.uk/codebox/email-sig/staff-sig.gif]
This email and any attachment may contain information that is confidential, privileged, or subject to copyright, and which may be exempt from disclosure under applicable legislation. It is intended for the addressee only. If you received this message in error, please let me know and delete the email and any attachments immediately. The University will not accept responsibility for the accuracy/completeness of this email and its attachments.

**Comment by wmshort** [comment]
I completely agree – that would be ideal. I think we are running up here against a somewhat different treatment of the lemma. ‘dog’ is here treated as simultaneously (or indifferently) a noun and a verb (you could also add in English an adverb (?): ‘I’m dog tired’, or maybe dog-tired is a fixed adjectival phrase). We could do the same for Latin, where ‘frumentarius’ would give you the nominal as well as adjectival synsets/senses indifferently. But for ‘dico’ do we want to lump together the several meanings of dico-are and dico-ere?
William Michael Short
Lecturer in Classics & Ancient History
University of Exeter
Phone: 01392 724794
E-mail: w.short@exeter.ac.uk
Amory Building, Rennes Drive, Exeter, Devon, EX4 4RJ
Ancient Greek WordNet<https://greekwordnet.chs.harvard.edu/> | Latin WordNet<https://latinwordnet.exeter.ac.uk/> | Cylleneus: Next-gen corpus search for ancient languages<https://github.com/cylleneus>
[http://www.exeter.ac.uk/codebox/email-sig/staff-sig.gif]
This email and any attachment may contain information that is confidential, privileged, or subject to copyright, and which may be exempt from disclosure under applicable legislation. It is intended for the addressee only. If you received this message in error, please let me know and delete the email and any attachments immediately. The University will not accept responsibility for the accuracy/completeness of this email and its attachments.

**Comment by kylepjohnson** [comment]
There's a lot here but I'll try to hit the main issues: (a) required vs optional parameters to `.lemma()`; (b) how the `WordNetProcess` should leverage POS tags from the pre-processed text ; (c) what to do when the input to `.lemma()` is ambiguous (meaning it returns more than one entry (eg, dog the verb and dog the noun).

(a) If possible, I'd like to see `WordNetCorpusReader.lemma()` look like this:

``` python
    def lemma((self, lemma, pos="", morpho="", return_ambiguous=True):
        """Takes ``lemma`` and finds matching headword.
        If ``pos`` or ``morph`` is provided, the results of found through 
        ``lemma`` alone are filtered. ``pos`` tags are in the form 
        or ``"n"`` for noun, , ``v`` for verb, etc. … .         
        """
        ...
```

(b) Thinking about the Process, one thing to be aware of is that you'll need to map the POS and morphological tags from our taggers into whatever terminology your wordnet needs (ie, "n" = verb). I can help you with this.

(c) What to do with ambiguity? You're right, it's the usual problem. I don't know but am open to suggestions. Until we have a great solution, I might vote we expose the problem to the user by giving an optional parameter to `lemma()` like `return_ambiguous` above (and I could add this param to the Process, too, probably). I could see times when a user would want stricter or looser matching for synsets (besides, I imagine and eg adjectival and verb forms are likely semantically related).

Bill, how do these sound as guiding principles?

**Comment by wmshort** [comment]
I think this makes good sense. I’ve started to implement your suggestions. I suspect Patrick can provide some insight here, too, as this a point where the WordNetProcess interacts with the prior lemmatization process – so whatever is coming out of that step will shape what is possible at this one. No problem for the mapping; it will be easy enough to roll a dict mapping the types, unless you have a better method in mind? Another question for Patrick (but also everyone) would be, given a set of ambiguous returned lemmas – say, dico-ere and dico-are or frumentarius-noun/substantive and frumentarius-adj – if the user has chosen to resolve these (return_ambiguous=False), what is the method of selection? It could simply be the first item, or based on a hierarchy like ‘noun-verb-adjective-adverb’, or based on some determination of ‘most likely’. I recall Patrick had been thinking along those lines somehow for the lemmatizer? Could an annotated corpus help determine percentage likelihoods for resolving ambiguous lemmas? (that is, sure, dico-ere and dico-are, are both possible given string ‘dico’, but dico-ere is more likely). Anyway, probably that is something that should be resolved at the moment of lemmatization and not at the level of the WordNetProcess.
William Michael Short
Lecturer in Classics & Ancient History
University of Exeter
Phone: 01392 724794
E-mail: w.short@exeter.ac.uk
Amory Building, Rennes Drive, Exeter, Devon, EX4 4RJ
Ancient Greek WordNet<https://greekwordnet.chs.harvard.edu/> | Latin WordNet<https://latinwordnet.exeter.ac.uk/> | Cylleneus: Next-gen corpus search for ancient languages<https://github.com/cylleneus>
[http://www.exeter.ac.uk/codebox/email-sig/staff-sig.gif]
This email and any attachment may contain information that is confidential, privileged, or subject to copyright, and which may be exempt from disclosure under applicable legislation. It is intended for the addressee only. If you received this message in error, please let me know and delete the email and any attachments immediately. The University will not accept responsibility for the accuracy/completeness of this email and its attachments.

**Pull request closed without merging**
